#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle (简化版)。
# 说明：本工程交付时未携带 gradle-wrapper.jar（二进制文件）。
# 客户侧直接用 Android Studio 打开本工程即可（AS 会自动按
# gradle/wrapper/gradle-wrapper.properties 下载 Gradle 7.6.4 并完成同步），
# 或在装有 Gradle 的机器上执行 `gradle wrapper` 重新生成完整 wrapper。
#

APP_BASE_NAME=$(basename "$0")
APP_HOME=$(cd "${APP_HOME:-./}" && pwd -P)
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -f "$CLASSPATH" ]; then
  # Normal path: use wrapper jar
  JAVACMD=${JAVA_HOME:+$JAVA_HOME/bin/java}
  JAVACMD=${JAVACMD:-java}
  exec "$JAVACMD" \
    -Xmx64m \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain "$@"
else
  echo "gradle-wrapper.jar 不存在。"
  echo "请改用 Android Studio 打开本工程构建，或执行: gradle wrapper"
  exit 1
fi
